version: '3.1'
services:
  stats-server:
    build: ./stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    environment:
        - POSTGRES_DB=stats
        - POSTGRES_USER=root2
        - POSTGRES_PASSWORD=root2

  ewm-service:
    build: ./ewm-server
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
