DROP TABLE IF EXISTS rating;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS compilations_events;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    rating INTEGER,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email),
    CONSTRAINT UQ_USER_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat real                                    NOT NULL,
    lon real                                    NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    annotation         VARCHAR(2000),
    category_id        INTEGER REFERENCES categories (id),
    confirmed_requests INTEGER,
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(7000),
    event_date         TIMESTAMP WITHOUT TIME ZONE,
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    initiator_id       INTEGER REFERENCES users (id),
    location_id        INTEGER REFERENCES locations (id),
    paid               boolean,
    participant_limit  INTEGER,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation boolean,
    state              VARCHAR(100),
    title              VARCHAR(150),
    views              INTEGER,
    rating             INTEGER,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned boolean,
    title  VARCHAR(200),
    CONSTRAINT pk_compilation primary key (id)
);

CREATE TABLE IF NOT EXISTS compilations_events
(
    event_id       BIGINT REFERENCES events (id) ON DELETE CASCADE,
    compilation_id BIGINT REFERENCES compilations (id) ON DELETE CASCADE,
    CONSTRAINT pk_compilation_event PRIMARY KEY (event_id, compilation_id)
);

CREATE TABLE IF NOT EXISTS requests
(
    created  TIMESTAMP WITHOUT TIME ZONE,
    event_id INTEGER REFERENCES events (id),
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  INTEGER REFERENCES users (id),
    status   VARCHAR(100),
    CONSTRAINT pk_request primary key (id)
);

CREATE TABLE IF NOT EXISTS rating
(
    event_id BIGINT REFERENCES events (id) NOT NULL,
    user_id BIGINT REFERENCES users(id) NOT NULL,
    reaction BOOLEAN,
    CONSTRAINT pk_rating PRIMARY KEY (event_id, user_id)
);

